### ISSUE TITLE
Buttons not properly shown in sidemenu using Ionic 3 framework

### ISSUE THREAD

**Issue by pablo-gonzalez** [MurhafSousli/ngx-sharebuttons#178]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

### Versions

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

local packages:

    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v7.10.0
    npm  : 3.10.10 
    OS   : Linux 4.4

Misc:

    backend : pro

### Repro steps

Install Ionic
`npm install -g ionic@latest`
Create a new Ionic 3 project using menu template
`ionic start sharebuttons-issue sidemenu`
Install font-awesome and ngx-sharebuttons
Put this code inside content tags in home.html and app.html
```
    <share-buttons [theme]="'default'"
    [include]="['facebook','twitter', 'telegram']"
    [url]="'http://twitter.com'">
    </share-buttons>
```
Run `ionic serve` to watch in browser

### The log given by the failure

First all thank you for this great component!

For some reason the class sb-show-template is added to the button element inside share-buttons component in the sidemenu.
Thus some space is taken from sb-content and the icon is not properly shown in the center of the button.

I would like to show the buttons in sidemenu. I am not facing this issue with version 3 of your component.

See attached images.

Thanks in advance,
Pablo
![captura de tela de 2017-11-02 19-17-37](https://user-images.githubusercontent.com/15030532/32351243-e24de114-c003-11e7-892a-d57b7c4d7e7b.png)
![captura de tela de 2017-11-02 19-18-22](https://user-images.githubusercontent.com/15030532/32351244-e2734364-c003-11e7-8050-12d330762db3.png)

**Comment by MurhafSousli** [comment]
Hi @pablo-gonzalez, `sb-template` class is only added when you use a single share button with a content, such as
```html
<share-button button="facebook">
   <div class="my-custom-template">Share!</div>
</share-button>
```
Is this happening only when put the buttons inside the sidebar menu or everywhere?

**Comment by pablo-gonzalez** [comment]
Hi @MurhafSousli 

It is happening only in sidemenu. Inside a page content is working fine.
The code for sharebutton component is the same for both cases so I do not know why sb-show-template is added!

**Comment by MurhafSousli** [comment]
@pablo-gonzalez it could be ionic sidebar manipulating the content inside the buttons somehow! This is how `sb-show-template` class is added

https://github.com/MurhafSousli/ngx-sharebuttons/blob/17f89a76645ca20e276918ac663d26f8abf76946/src/components/share-button/share-button.component.html#L11

https://github.com/MurhafSousli/ngx-sharebuttons/blob/17f89a76645ca20e276918ac663d26f8abf76946/src/components/share-button/share-button.component.html#L34-L37

Can you try wrapping the share buttons component in div container?

**Comment by pablo-gonzalez** [comment]
I have tried putting the component in div container and nothing has changed.
I have realized that after clicking on the button the class sb-show-template is removed from the button in sidemenu.

Could you try to follow the steps to reproduce please? I can not figure out how to fix this.

Thanks

**Comment by MurhafSousli** [comment]
@pablo-gonzalez I think you can fix it with css, try something like
```css
.sb-template {
   display: none !important;
} 
```
I also pushed new themes in v4.1.0 that might fix this

**Comment by pablo-gonzalez** [comment]
Hi @MurhafSousli 

Your code did not fix the issue but your approach helped me to fix it using this code:

```
.sb-show-text .sb-icon, .sb-show-template .sb-icon {
    //width: 2em;
    width: 100% !important;
  }

.sb-default .sb-wrapper.sb-show-icon.sb-show-template .sb-template {
    //padding-right: 1em;
    padding-right: 0 !important;
    padding-left: 0;
}
```
I have commented the lines that are causing the width decrease in div with sb-icon class and the width increment in div with class sb-template which are produced by the unexpected addition of class sb-show-template in the share buttons component in sidemenu area.

Although it is not ideal it worked as a workaround.

If you want to understand what is causing this issue you can follow the simple steps to reproduce it.

Thank you very much for your support,
Pablo

**Comment by MurhafSousli** [comment]
@pablo-gonzalez Thanks for sharing
