### ISSUE TITLE
npm i @ngx-sharebuttons @angular/cdk

### ISSUE THREAD

**Issue by rnkpareek** [MurhafSousli/ngx-sharebuttons#460]
npm i @ngx-sharebuttons @angular/cdk while  running this in termial it gives error as
 Invalid tag name "@ngx-sharebuttons": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:

**Comment by MurhafSousli** [comment]
it is `ngx-sharebuttons` not `@ngx-sharebuttons`

**Comment by aldeen** [comment]
Documentation should then be fixed here - https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Directive

**Comment by timofeysie** [comment]
Documentation still not fixed: https://github.com/MurhafSousli/ngx-sharebuttons/wiki/Share-Button-Directive

**Comment by MurhafSousli** [comment]
Sorry, that one slipped from me, it is fixed now, thanks!
